autoprefixer:
  browsers: ["> 1%", "last 2 versions", "Firefox ESR", "Opera 12.1"]
browserify:
  extensions: .coffee
imagemin:
  progressive: true
  svgoPlugins: [removeViewBox: false]
minify_html:
  conditionals: true
  quotes: true
sass:
  sourcemap: none
  compass: true
  bundleExec: true
